### PR TITLE
integrate OAuth authentication tracking under single category

### LINKED ISSUE #265: 🐛 [BUG] - Update OAuth login tracking to integrate methods under single category
### Description

our login analytics show ~105 (avg.) logins falling under "(not yet)" category, indicating we're not properly tracking some OAuth auth methods. We need to integrate all OAuth logins under a single "oauth" tracking category in our analytics

Current behavior:
OAuth logins are mapped to different categories through providerToLoginMethod. Some OAuth providers appear to fall through and register as "(not yet)" in analytics

Expected behavior:
All OAuth logins tracked under consistent "oauth" category

### Reproduction steps

```bash
1. Go to https://eu.mixpanel.com/s/49Bmp3
2. Scroll down to the table of unique users by `loginMethod`
```

### Kit Version

^1.6.1

### Connection Details Screenshot

Image

### PR DESCRIPTION
**Pull request by Jennievon**
### Description
This PR updates our OAuth login tracking to use a consistent "oauth" value rather than mapping different providers to various login methods

Closes #265 

### Updated packages (if any):
-  [x] vechain-kit

### CODE REVIEW

File: packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts [hunk 1]
```diff
@@ -30,7 +23,7 @@ export const useLoginWithOAuth = () => {
     const { user } = usePrivy();
 
     const initOAuth = async ({ provider }: OAuthOptions) => {
-        const loginMethod = providerToLoginMethod[provider];
+        const loginMethod = VeLoginMethod.OAUTH;
```
Comment (Agilulfo1820) [inline packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts:26]: is this right though?

**Review by Agilulfo1820 — APPROVED** [review]

File: packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts (hunk 1 above)
Comment (victhorbi) [reply packages/vechain-kit/src/hooks/login/useLoginWithOAuth.ts:26]: Sorted out during the standup. Looks good.
