### PR TITLE
Fix/get avatar

### LINKED ISSUE #196: 🐛 [BUG] - useGetAvatarOfAddress image refresh
### Description

 It takes some time refreshing data + query is not updated after switching/adding vet domain

### Reproduction steps

```bash
1. Go to vebetterdao governance dapp
2. Click on the wallet
3. Update avatar
4. Avatar is updated
5. Refresh the page, it will show previous image


1. Login
2. Claim a domain
3. Add avatar
4. Claim another domain
5. It will still display previous avatar
6. Refresh the page avatar is updated
```

### Kit Version

1.5.10

### Connection Details Screenshot

_No response_

### PR DESCRIPTION
**Pull request by Agilulfo1820**
#### Avatar issue
- Using https://vet.domains/api/avatar/ proxy to fetch the avatar of a domain so we can avoid the CORS issue we have with some NFT collections (Keeping the old hook as legacy, the code could be useful in the future if we decide to create our own proxy)
- Removed stale time on the avatar

#### Domain issue
- There was also a bug when claiming an existing primary .vet domain, our `useClaimVeWorldDomain` was not handling that scenario
- I added an "Unset domain" to allow a user to get rid of his domain and just use the wallet address
- Divided the claim domain hooks in 3 different ones, so we can separate responsibilities and make code readability easier

Closes #196 

Demo

https://github.com/user-attachments/assets/02e544a3-0a5b-4e77-becf-d03f503132b8

https://github.com/user-attachments/assets/f4955dd0-4f1b-4cf6-89c2-9616bc63a4ec

### Updated packages (if any):

-  [ ] next-template
-  [x] homepage
-  [x] vechain-kit

### CODE REVIEW

File: packages/vechain-kit/src/hooks/api/vetDomains/useClaimVeWorldSubdomain.ts [hunk 1]
```diff
@@ -38,16 +44,43 @@ export const useClaimVeWorldSubdomain = ({
...
+                abi: ReverseRegistrarInterface.getFunction('setName'),
+            });
+
+            return clausesArray;
+        }
+
         if (!subdomain) throw new Error('Invalid subdomain');
 
-        const clausesArray: any[] = [];
+        const fullDomain = `${subdomain}.${domain}`;
```
Comment (victorkl400) [inline packages/vechain-kit/src/hooks/api/vetDomains/useClaimVeWorldSubdomain.ts:81]: I think `${subdomain}.${domain}` could be a helper function to avoid template strings everywhere

**Review by victorkl400 — APPROVED** [review]
LGTM, left some suggestions , but can be tackled later
